//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lab20.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public string Item_Name { get; set; }
        public double Item_Price { get; set; }
        public string Item_Quantity { get; set; }
        public string Item_Description { get; set; }
    }
}
